#!/usr/bin/env python3
"""Generate per-plugin requirements.lock from plugin.toml dependencies.

Uses `uv pip compile --universal --generate-hashes` so one lockfile covers
all target platforms (macOS + Windows) and pins every dependency
(top-level + transitive) to an exact version + sha256 hash.

Resolution is frozen with `--exclude-newer EXCLUDE_NEWER` so re-running is
deterministic: an upstream release does not silently change the lock and
does not flap CI. To adopt newer versions, bump EXCLUDE_NEWER and re-run.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib  # type: ignore[import-untyped,no-redef]

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"

# Bundled plugin runtime version (python-build-standalone) shipped by the
# main app. Keep in sync with MAGI_PLUGIN_PYTHON_VERSION in the magi repo.
PYTHON_VERSION = "3.13"

# Freeze dependency resolution at this instant. Bump deliberately to adopt
# newer upstream releases; never auto-follow. See module docstring.
EXCLUDE_NEWER = "2026-05-31T00:00:00Z"
EXCLUDE_NEWER_PACKAGES = {
    # osxphotos 0.75.9 resolves pyobjc 9.2, which does not build cleanly on
    # the bundled Python 3.13 runtime. Allow only this package to move far
    # enough to pick up the pyobjc 12.x-compatible release.
    "osxphotos": "2026-06-15T00:00:00Z",
}

LOCK_HEADER = (
    "# This file is auto-generated by scripts/lock-deps.py. Do not edit.\n"
    "# Regenerate with: python scripts/lock-deps.py <plugin_dir_name>\n"
)


def read_dependencies(plugin_dir: Path) -> list[str]:
    toml_path = plugin_dir / "plugin.toml"
    if not toml_path.exists():
        return []
    with open(toml_path, "rb") as fh:
        data = tomllib.load(fh)
    deps = data.get("plugin", {}).get("dependencies", [])
    return [str(dep) for dep in deps]


def compile_lock(dependencies: list[str]) -> str:
    reqs_text = "\n".join(dependencies) + "\n"
    cmd = [
        "uv", "pip", "compile",
        "--universal",
        "--generate-hashes",
        "--python-version", PYTHON_VERSION,
        "--exclude-newer", EXCLUDE_NEWER,
    ]
    for package, timestamp in EXCLUDE_NEWER_PACKAGES.items():
        cmd.extend(["--exclude-newer-package", f"{package}={timestamp}"])
    cmd.extend(
        [
            "--no-header",
            "-",  # read requirements from stdin
        ]
    )
    try:
        result = subprocess.run(
            cmd, input=reqs_text, capture_output=True, text=True, check=True
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            f"uv pip compile failed (exit {exc.returncode}):\n{exc.stderr}"
        ) from exc
    return LOCK_HEADER + result.stdout


def lock_path_for(plugin_dir: Path) -> Path:
    return plugin_dir / "requirements.lock"


def iter_plugin_dirs(only: str | None) -> list[Path]:
    if only:
        target = PLUGINS_DIR / only
        if not target.is_dir():
            raise SystemExit(f"No plugin directory named: {only}")
        return [target]
    return [d for d in sorted(PLUGINS_DIR.iterdir()) if d.is_dir()]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("plugin", nargs="?", help="Limit to this plugin dir name")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if any lockfile is stale or missing",
    )
    args = parser.parse_args()

    drift = False
    for plugin_dir in iter_plugin_dirs(args.plugin):
        deps = read_dependencies(plugin_dir)
        lock_file = lock_path_for(plugin_dir)

        if not deps:
            # No declared deps: a stray lockfile must not exist.
            if lock_file.exists():
                if args.check:
                    print(f"STALE (should not exist): {lock_file}")
                    drift = True
                else:
                    lock_file.unlink()
                    print(f"  - removed {lock_file}")
            continue

        new_text = compile_lock(deps)
        if args.check:
            existing = lock_file.read_text() if lock_file.exists() else ""
            if existing != new_text:
                print(f"STALE: {lock_file}")
                drift = True
        else:
            lock_file.write_text(new_text)
            print(f"  + {lock_file}")

    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
